#### 1.	[11 pts] The formula for determining the monthly payment $p$ for a loan of $L$ over $m$ months with an annual interest rate of $r$ is given by 
$$p=\frac{(\frac{r}{12} L)}{1-\left(1+\frac{r}{12} \right)^{-m} }$$

a) Suppose you buy a car for \\$  40,000 with a 5% interest rate.  If you pay it back over 5 years, what is your monthly payment (to the nearest cent)? [1 pt]

For this we simply plug in the given values

$$
p=\frac{(\frac{0.05}{12} \cdot 40000)}{1-\left(1+\frac{0.05}{12} \right)^{-5*12} } \\
p =$754.54
$$

b) Now suppose you pay this monthly payment for two years and then get a raise.  Desiring to pay the loan back as soon as possible, you increase the payment by \$50 a month.  Then, after one more years, you receive another raise, and you increase your monthly payment by another \$30.  Use a simulation in Python to show how soon you will be able to pay back the loan.  Print the month-by-month payment of the principal, the interest and the remaining amount of the loan. [10 pts]

In [ ]:
import numpy as np 
import pandas as pd

In [ ]:
#Code answer here

#initializing 
m=60
initial_pay = 754.547406
third_year_pay = initial_pay + 50
fourth_year_pay = third_year_pay + 30

interest_payment =np.zeros(m)
principle_payment = np.zeros(m)
loan = np.zeros(m)
loan[0] = 40000
monthly_pay = np.zeros(m)


def monthly_pay( apr,month):
  global balance 
  balance = []
  if month == 0:
    outstanding_balance = 40000
  while outstanding_balance > 0:
    interest_payment[month] = outstanding_balance * (apr/12)
    if month < 24:
      principle_payment[month] = initial_pay - interest_payment[month]
    if month >=24 and month <36: 
      principle_payment[month] = third_year_pay - interest_payment[month]
    if month >=36:
      principle_payment[month] = fourth_year_pay - interest_payment[month] 
    
    outstanding_balance -= principle_payment[month]
    balance.append(outstanding_balance)
    month += 1 
  return(month, principle_payment, interest_payment)

test = monthly_pay(apr = 0.05, month = 0)
# test = pd.DataFrame(test[(1,2)],columns = ["principle payment", "interest payment"])
indices = [1,2]
test2 = [test[index] for index in indices]
# test2[0]

principle_list = []
interest_list = []
for i in range(len(test2[0]+1)):
  principle_list.append(test2[0][i])
  interest_list.append(test2[1][i])

principle_list
interest_list
# test3 = pd.DataFrame(test2,columns = ["principle payment", "interest payment"])
df_p = pd.DataFrame(principle_list, columns = ["Monthly Principle"])
df_i = pd.DataFrame(interest_list, columns = ["Monthly Interest"])
df_b = pd.DataFrame(balance, columns = ["Monthly Balance Remaining"])
pd.concat([df_i,df_p,df_b],axis=1)

    Monthly Interest  Monthly Principle  Monthly Balance Remaining
0         166.666667         587.880739               39412.119261
1         164.217164         590.330242               38821.789018
2         161.757454         592.789952               38228.999066
3         159.287496         595.259910               37633.739157
4         156.807246         597.740160               37035.998997
5         154.316662         600.230744               36435.768254
6         151.815701         602.731705               35833.036549
7         149.304319         605.243087               35227.793462
8         146.782473         607.764933               34620.028528
9         144.250119         610.297287               34009.731241
10        141.707214         612.840192               33396.891049
11        139.153713         615.393693               32781.497355
12        136.589572         617.957834               32163.539522
13        134.014748         620.532658               31543.006864
14        131.429195         623.118211               30919.888653
15        128.832869         625.714537               30294.174116
16        126.225725         628.321681               29665.852436
17        123.607718         630.939688               29034.912748
18        120.978803         633.568603               28401.344145
19        118.338934         636.208472               27765.135673
20        115.688065         638.859341               27126.276333
21        113.026151         641.521255               26484.755078
22        110.353146         644.194260               25840.560818
23        107.669003         646.878403               25193.682416
24        104.973677         699.573729               24494.108686
25        102.058786         702.488620               23791.620067
26         99.131750         705.415656               23086.204411
27         96.192518         708.354888               22377.849523
28         93.241040         711.306366               21666.543157
29         90.277263         714.270143               20952.273014
30         87.301138         717.246268               20235.026746
31         84.312611         720.234795               19514.791951
32         81.311633         723.235773               18791.556178
33         78.298151         726.249255               18065.306923
34         75.272112         729.275294               17336.031629
35         72.233465         732.313941               16603.717688
36         69.182157         765.365249               15838.352439
37         65.993135         768.554271               15069.798168
38         62.790826         771.756580               14298.041588
39         59.575173         774.972233               13523.069355
40         56.346122         778.201284               12744.868072
41         53.103617         781.443789               11963.424283
42         49.847601         784.699805               11178.724478
43         46.578019         787.969387               10390.755091
44         43.294813         791.252593                9599.502497
45         39.997927         794.549479                8804.953019
46         36.687304         797.860102                8007.092917
47         33.362887         801.184519                7205.908398
48         30.024618         804.522788                6401.385610
49         26.672440         807.874966                5593.510644
50         23.306294         811.241112                4782.269533
51         19.926123         814.621283                3967.648250
52         16.531868         818.015538                3149.632711
53         13.123470         821.423936                2328.208775
54          9.700870         824.846536                1503.362239
55          6.264009         828.283397                 675.078842
56          2.812829         831.734577                -156.655735
57          0.000000           0.000000                        NaN
58          0.000000           0.000000                        NaN
59          0.000000           0.000000                        NaN

#### 2.	[14 pts] You have a friend that wants to play an unusual game with you.  She flips a fair coin, recording the number of heads and tails flipped, until the difference of between the heads and tails is three.  At that time, the game ends and the number of times the coin was flipped is noted.  The payoff to you is \$10 minus \$1 for every time the coin was flipped.  A negative payoff means that you pay your friend that amount of money.  Oh, and because your friend invented this game, she requires you to pay \$1 every time you play it.

In this question, we wil progressively build a simulation to answer the question, "Should you play the game?"

The strategy for building the simulation is to build functions that simulate 1) flipping a coin, 2) playing one game, 3) playing multiple games to calculate an average, and 4) replicating the multiple games so that we can calculate an average of averages which, if we do this correctly, is significantly more normally distributed than the original game. (If you need a brush up on this from your stats class, please come to my office hour or set up a time on my calendar.)

As you build your code, I suggest that you test each of the functions to make sure they are doing what you want them to do.

With that, here we go!

a) Build a python function that returns "Heads" or "Tails" representing a flip of a fair coin.  To do this, use a list with the values "Heads" and "Tails" and use the [`integers`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html) method of the `numpy.random.default_rng()` Generator.  [2 pts]

In [ ]:
from numpy import random
import numpy as np
from numpy.random import default_rng
import scipy.stats as st

rng = default_rng(2020) # rng stands for Random Number Generator; the seed is set to 2020

#Code answer here
def coin_flip():
  coin_list = ["Heads", "Tails"]
  x = rng.integers(1,3)
  if x == 1:
    coin = coin_list[0]
  if x == 2:
    coin = coin_list[1]
  return(coin)
coin_flip()

'Heads'

b) Now, add to this a Python function that returns the outcome of a game.  You may want to use the Python function `abs()` to calculate the absolute value. Make sure it returns the dollars won or lost as a result of playing the game. [3 pts]

In [ ]:
#Code answer here


def game():
  single_game_results= []
  cum_heads = 0
  cum_tails = 0
  coin_flip_count = 0
  while abs(cum_heads - cum_tails) < 3: 
    coin_flip
    coin = coin_flip()
    coin_flip_count += 1
    if coin == "Heads":
      cum_heads += 1
    if coin == "Tails":
      cum_tails += 1
    single_game_results.append(coin)
  payoff = 10 - coin_flip_count - 1
  return(payoff, single_game_results)



game()

(4, ['Heads', 'Tails', 'Tails', 'Tails', 'Tails'])

c) Next, add a Python function that repeats the game a number of times and returns the average result.  Define a variable called `samples` which is the number of times the game is played.  Capture each outcome in a numpy array called `results` and return the average of these results. [3 pts]

In [ ]:
#Code answer here

samples = 100
def multiple_games():
  results = np.array([])
  one_game_payoff = game()[0]
  for i in range(samples):
    game()
    results = np.append(results, one_game_payoff)
  return(sum(results)/samples)
multiple_games()

4.0

d) Congratulations! You are almost there.  Finally, add the code replicates the averages. Do not add this as a function.  Create a variable `replications` for the number of averages you will collect and a numpy array called `averages` for ... \
\
That's right, you guessed it, each of the averages. [3 pts]

In [ ]:
#Code answer here
replications = 10000
averages = np.array([])
for i in range(replications): 
  multiple_games()
  average = multiple_games()
  averages = np.append(averages, average)

averages

array([  2.,  -8.,   0., ...,   6.,   0., -30.])

In [ ]:
average_of_averages = sum(averages)/replications
average_of_averages
print(st.t.interval(alpha=0.95, df=len(averages)-1, loc=np.mean(averages), scale=st.sem(averages)))
print(average_of_averages)

(-0.14484236352490112, 0.12804236352490114)
-0.0084

e) Now to the answer. Run the simulation with 10,000 replications of the averages which contain 100 samples. Calculate and print out the average of the averages along with the 95% confidence interval for these averages. What is your conclusion about playing this game? [3 pts]

My conclusion is that I will, over the long run, make very little money and therefore it's not worth it.

#### 3.	[13 pts] Consider the population simulation we developed in class. Below is a version adapted to run the simulation multiple times to estimate the probability that this population can sustain itself.  Please review this version and contact me if you have specific questions on how it works.  Try it out to make sure it works for you.  Your result will vary, but it should be about 0.36 - 0.38.(Note: I had some trouble with the initialization.  I'm sure there is a more elegant way to do this, but it works!)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

rng = np.random.default_rng(2020) #random number generator; seed to 2020 for replicability

#Constants
init_start_age = 18
init_end_age = 50

fertility_start = 18
fertility_end = 40
baby_odds = 0.25 #chance of birth 
infant_mortality_reduction = 0.999 #reduction of death rate 

old_person = 60
old_death_odds = 0.1

max_population = 10000
end_year = 200
 
samples = 1000

#Variables
infant_mortality = 0.6 #death rate 

population = np.zeros(10000) 
population[0] = 50 #Initial population is 50 
peopleDictionary = [] #Filled with the age and gender of people 
results = np.zeros(samples)

class person:
    def __init__(self, age):
        self.gender = rng.integers(2) # 1 above maximum desired value.
        self.age = age
       

def initialize():
    global infant_mortality
    infant_mortality = 0.8
    for individual in range(int(population[0])):
        peopleDictionary.append(person(rng.integers(init_start_age, init_end_age + 1)))

def birth(infant_mortality):
    births = 0
    for individual in peopleDictionary:
        if individual.gender == 1 and \
           individual.age > fertility_start and \
           individual.age < fertility_end and \
           rng.random() <= baby_odds * (1 - infant_mortality):
              peopleDictionary.append(person(0))
              births += 1
    return births

def death(individual):
    died = False
    if individual.age > old_person \
        and rng.random() <= old_death_odds:
                peopleDictionary.remove(individual)
                died = True
    return died

def one_year(infant_mortality):
    deaths = 0
    births = birth(infant_mortality)
    for individual in peopleDictionary:
        if not(death(individual)):
            individual.age +=1
        else:
            deaths +=1
    return births, deaths

def sustain():
    global infant_mortality
    year = 0
    initialize()
    outcome = 1
    while population[year] < max_population and population[year] > 1 and year < end_year:
        births, deaths = one_year(infant_mortality) 
        year += 1
        infant_mortality *= infant_mortality_reduction
        population[year] = len(peopleDictionary)
        
    peopleDictionary.clear()
    if population[year]<=1:
        outcome = 0
    return outcome

for sample in range(samples):
    results[sample] = sustain()
np.mean(results)

0.389

In the current simulation, the population is not constrained by potential food shortages.  Represent food by a variable called “food” which is expressed in annual nutritional units (ANUs).  One ANU feeds one person each year, and each person consumes one ANU each year. If "food" drops below the number in the population, the difference is the number of people in the population that starve and must be deleted from the population that year. 

Food is produced by farmers during the annual harvest.  Farmers are 50% of the people between the ages of 15 and 60. “Able farmers” this year are farmers except those women farmers that gave birth this year.  Assume half of the births were were by women farmers.

Each “able farmer” produces enough food for themself and two other people. Unfortunately, crop failures occur randomly with probability 0.2 each year.  When this happens, only ¼ of the annual production of food occurs.  Assume that “food” is non-perishable.

b) To represent the accumulation of food and the annual impact of consumption and possible starvation, add a harvest function to the population simulation.  Add code according to the following steps: \
>    1) Calculate the "able farmers".  [Note: for this calculation, you will need to pass the number of births into your harvest function.] [4 pts] \
>    2) Determine if a crop failure occurred [1 pt] \
>    3) Add the appropriate amount of new food to food [1 pt] \
>    4) Based on the total food, determine if a shortage occurred.  If so, set food to zero and remove from the peopleDitionary keys 0 to the integer value of shortage amount (see the del command for dictionaries).  Otherwise, decrease the total food by the number of people in the population. [3 pts]

In [ ]:
#Put your full code here

new_dic = []

#new initialization function 
year = 0
def init2():
  for individual in range(int(population[year])):
    peopleDictionary.append(person(rng.integers(init_start_age, init_end_age + 1)))
    new_dic.append(peopleDictionary[individual]) #Here we make a new list called new_dic and append all the persons to it 
  return(new_dic) #We return this list to use in the able_farmers() function 
    
   
def able_farmers():
  final_farm = 0  
  new_dic = init2() #We set the new_dic = to the output of the function above
  init2() #We run the above function
  able_farmer_count = 0 #Initilaizing a counter for able farmers
  births = birth(infant_mortality) #Including the birth function to check for farmer women giving birth 
  #Creating a for loop to loop through the people list we created and check 
  #each person to see if they are an able farmer 
  for i in new_dic: 
    #First we check to see if they are within the age range of 15 and 60 
    if i.age >= 15 and i.age<=60:
      #Next we use an rng to simulate 50% of the people in the age range being farmers 
      final_farm = rng.integers(2)
    #here we are checking to see if they fall within the 50% of farmers 
    if final_farm == 1:
      #Below we check if they are male or if they gave birth. If they are male 
      #then they are an able farmer
      #If they are female, then we check if they gave birth. 
      if i.gender == 0 or births == 0: 
        able_farmer_count += 1
  return(able_farmer_count)


able_farmers2 = 0 
total_food=np.zeros(10000)

def harvest_one_year(year):
  #Below we set a virable equal to the previous functions output
  able_farmers2 = able_farmers()
  #Here we initialize the probability of crop failure being 0.2
  crop_failure = rng.integers(1,11) #10 random numbers 
  if crop_failure == 1 or crop_failure == 2: #If they are a 1 or 2 then it
    #satisfies the 0.2 probability 
    for i in range(able_farmers2+1): #Here we apply the 0.25 
      new_food = (able_farmers2 * 3) * 0.25
  else: 
    for i in range(able_farmers2+1):#Here we have a normal harvest
      new_food = (able_farmers2 * 3)
    #Below we set a variable total_food to equal itself plus the new_food harvested 
    total_food[year] = total_food[year-1] + new_food 

  #Here thr function returns the total food for that year 
  return(total_food[year])


def sustain():
    global infant_mortality
    year = 0
    initialize()
    outcome = 1
    #Here we use below function to count the number of able farmers this year 
    able_farmers()
    #Below we then calculate the abvailable harvest this year 
    harvest_one_year(year)
    while population[year] < max_population and population[year] > 1 and year < end_year:
        births, deaths = one_year(infant_mortality) 
        year += 1
        infant_mortality *= infant_mortality_reduction
        population[year] = len(peopleDictionary)
        
    peopleDictionary.clear()
    new_dic.clear()
    #We take the differance of the food and the population 
    diff_food = (total_food[year] - population[year] )
    if population[year]<=1 or diff_food < 0:
        outcome = 0
        #If the difference is negative, all food for this year is 0, and 
        #when used in the differnece equation to calculate the next years food, it will be zero 
        total_food[year] = 0 
        #Here we kill off the people from the beginning of the dictionary 
        #to the absolute value number of places of the difference in food
        del peopleDictionary[0:abs(int(diff_food))]
    else:
      #If the difference is positive, then the food left for this year 
      #will just be the difference 
      total_food[year] = diff_food
    return outcome
for sample in range(samples):
    results[sample] = sustain()
np.mean(results)

0.0

c) Finally, run your code and provide your estimate for the probability of the population sustaining itself.

The estimate is 0%. It leads to a downard spiral over and over again due to the probabilities of crop failure and the consumption of food.